### ISSUE TITLE
Deno 1.7 import errors with ts-prometheus v0.1.0

### ISSUE THREAD

**Issue by shah** [marcopacini/ts-prometheus#3]
Hi @marcopacini thanks for putting this module together. I was trying to use it with Deno 1.7 and was getting these errors on import:

```typescript
Download https://denopkg.com/marcopacini/ts-prometheus@v0.1.0/mod.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/mod.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/histogram.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/metric.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/registry.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/counter.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/gauge.ts
Download https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/collector.ts
Check https://denopkg.com/marcopacini/ts-prometheus@v0.1.0/mod.ts
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Metric, Inc, Dec, Set, Observe } from "./metric.ts";
                 ~~~
    at https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/mod.ts:4:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Metric, Inc, Dec, Set, Observe } from "./metric.ts";
                      ~~~
    at https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/mod.ts:4:23

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Metric, Inc, Dec, Set, Observe } from "./metric.ts";
                           ~~~
    at https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/mod.ts:4:28

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Metric, Inc, Dec, Set, Observe } from "./metric.ts";
                                ~~~~~~~
    at https://raw.githubusercontent.com/marcopacini/ts-prometheus/v0.1.0/mod.ts:4:33

Found 4 errors.
```

Is this something you've run across before?

**Comment by marcopacini** [comment]
@shah Thank you for reporting. Since version 1.5 Deno enables the `isolatedModules` TypeScript compiler option for all users by default like reported in [release notes](https://deno.land/posts/v1.5#stricter-type-checks-in-stable).
